//////////////////////////////////////////////////////////////////////
// This file was automatically generated by CLIF to run under Python 3
// Version 0.3
//////////////////////////////////////////////////////////////////////
// source: /pykaldi/kaldi/rnnlm/rnnlm-compute-state.clif

#include <Python.h>

namespace __rnnlm__compute__state_clifwrap {

bool Ready();
PyObject* Init();

}  // namespace __rnnlm__compute__state_clifwrap

PyMODINIT_FUNC PyInit__rnnlm_compute_state(void) {
  if (!__rnnlm__compute__state_clifwrap::Ready()) return nullptr;
  return __rnnlm__compute__state_clifwrap::Init();
}
