//////////////////////////////////////////////////////////////////////
// This file was automatically generated by CLIF to run under Python 3
// Version 0.3
//////////////////////////////////////////////////////////////////////
// source: /pykaldi/kaldi/tree/cluster-utils.clif

#include <Python.h>

namespace __cluster__utils_clifwrap {

bool Ready();
PyObject* Init();

}  // namespace __cluster__utils_clifwrap

PyMODINIT_FUNC PyInit__cluster_utils(void) {
  if (!__cluster__utils_clifwrap::Ready()) return nullptr;
  return __cluster__utils_clifwrap::Init();
}
