//////////////////////////////////////////////////////////////////////
// This file was automatically generated by CLIF to run under Python 3
// Version 0.3
//////////////////////////////////////////////////////////////////////
// source: /pykaldi/kaldi/decoder/training-graph-compiler-ext.clif

#include <Python.h>

namespace __training__graph__compiler__ext_clifwrap {

bool Ready();
PyObject* Init();

}  // namespace __training__graph__compiler__ext_clifwrap

PyMODINIT_FUNC PyInit__training_graph_compiler_ext(void) {
  if (!__training__graph__compiler__ext_clifwrap::Ready()) return nullptr;
  return __training__graph__compiler__ext_clifwrap::Init();
}
