//////////////////////////////////////////////////////////////////////
// This file was automatically generated by CLIF to run under Python 3
// Version 0.3
//////////////////////////////////////////////////////////////////////
// source: /pykaldi/kaldi/lat/word-align-lattice.clif

#include <Python.h>

namespace __word__align__lattice_clifwrap {

bool Ready();
PyObject* Init();

}  // namespace __word__align__lattice_clifwrap

PyMODINIT_FUNC PyInit__word_align_lattice(void) {
  if (!__word__align__lattice_clifwrap::Ready()) return nullptr;
  return __word__align__lattice_clifwrap::Init();
}
