//////////////////////////////////////////////////////////////////////
// This file was automatically generated by CLIF to run under Python 3
// Version 0.3
//////////////////////////////////////////////////////////////////////
// source: /pykaldi/kaldi/fstext/fst.clif

#include <Python.h>

namespace __fst_clifwrap {

bool Ready();
PyObject* Init();

}  // namespace __fst_clifwrap

PyMODINIT_FUNC PyInit__fst(void) {
  if (!__fst_clifwrap::Ready()) return nullptr;
  return __fst_clifwrap::Init();
}
