//////////////////////////////////////////////////////////////////////
// This file was automatically generated by CLIF to run under Python 3
// Version 0.3
//////////////////////////////////////////////////////////////////////
// source: /pykaldi/kaldi/fstext/push-special.clif

#include <memory>
#include "clif/python/optional.h"
#include "fstext/push-special.h"
#include "clif/python/postconv.h"
// This module defines no types.
