//////////////////////////////////////////////////////////////////////
// This file was automatically generated by CLIF to run under Python 3
// Version 0.3
//////////////////////////////////////////////////////////////////////
// source: /pykaldi/kaldi/base/io-funcs.clif

#include <memory>
#include "clif/python/optional.h"
#include "base/io-funcs.h"
#include "clif/python/postconv.h"
// This module defines no types.
