//////////////////////////////////////////////////////////////////////
// This file was automatically generated by CLIF to run under Python 3
// Version 0.3
//////////////////////////////////////////////////////////////////////
// source: /pykaldi/kaldi/matrix/compressed-matrix.clif

#include <memory>
#include "clif/python/optional.h"
#include "matrix/compressed-matrix.h"
#include "clif/python/postconv.h"

namespace kaldi {
using namespace ::clif;

// CLIF use `::kaldi::CompressedMatrix` as CompressedMatrix
bool Clif_PyObjAs(PyObject* input, ::kaldi::CompressedMatrix** output);
bool Clif_PyObjAs(PyObject* input, std::shared_ptr<::kaldi::CompressedMatrix>* output);
bool Clif_PyObjAs(PyObject* input, std::unique_ptr<::kaldi::CompressedMatrix>* output);
bool Clif_PyObjAs(PyObject* input, ::kaldi::CompressedMatrix* output);
bool Clif_PyObjAs(PyObject* input, ::gtl::optional<::kaldi::CompressedMatrix>* output);
PyObject* Clif_PyObjFrom(::kaldi::CompressedMatrix*, py::PostConv);
PyObject* Clif_PyObjFrom(std::shared_ptr<::kaldi::CompressedMatrix>, py::PostConv);
PyObject* Clif_PyObjFrom(std::unique_ptr<::kaldi::CompressedMatrix>, py::PostConv);
PyObject* Clif_PyObjFrom(const ::kaldi::CompressedMatrix&, py::PostConv);
// CLIF use `::kaldi::CompressionMethod` as CompressionMethod
bool Clif_PyObjAs(PyObject* input, ::kaldi::CompressionMethod* output);
PyObject* Clif_PyObjFrom(const ::kaldi::CompressionMethod&, py::PostConv);

}  // namespace kaldi

// CLIF init_module if (PyObject* m = PyImport_ImportModule("_compressed_matrix")) Py_DECREF(m);
// CLIF init_module else goto err;
