//////////////////////////////////////////////////////////////////////
// This file was automatically generated by CLIF to run under Python 3
// Version 0.3
//////////////////////////////////////////////////////////////////////
// source: /pykaldi/kaldi/matrix/tp-matrix.clif

#include <Python.h>

namespace __tp__matrix_clifwrap {

bool Ready();
PyObject* Init();

}  // namespace __tp__matrix_clifwrap

PyMODINIT_FUNC PyInit__tp_matrix(void) {
  if (!__tp__matrix_clifwrap::Ready()) return nullptr;
  return __tp__matrix_clifwrap::Init();
}
